### ISSUE TITLE
website is down :(

### ISSUE THREAD

**Issue by jackrobbi** [mhelmetag/surfcam-magician#38]
the site is down :( this was my saving grace lol

**Comment by mhelmetag** [comment]
Yeah... sorry, friend. It was a good ride while it lasted!

From the readme:
> Surfline finally started blocking cross origin requests so I've stopped hosting this publicly. It's possible to get around this but I'm going to stop hosting a site that makes direct requests so I don't totally ruin access to their APIs. Feel free to host locally and tinker away!

**Comment by jackrobbi** [comment]
dude -- legendary run. thank you for hosting it for as long as you did. you rock.

**Comment by mhelmetag** [comment]
It's back, baby!
